import React from 'react';
import "./privacy.css";


const Terms_Condition = () => {
  return (
    <>
    <div className='terms-background'>
        <div className='terms-condition-main'>
            <h2 className='terms-header'>TERMS & CONDITION</h2>
            <ol className='terms-list-items'>
                <li><b>Contract Formation and Overview</b></li>
                <p className='terms-first-list'><b>1.1</b><br/>Business IT and services Pty Ltd T/as Moneyfirst ("Moneyfirst," "we," "us," or "our") is a Australian corporation with its headquarters at Add 28 harriet lane Oxenford QLD 4210 , Australia. These terms and conditions (the "Terms and Conditions") govern the terms under which you, as defined in Paragraph 1.2, may access this Application and use the services associated with it (the "Service"). By accessing, registering and using the Service, you agree to be bound by these Terms and Conditions.</p>
                <p className='terms-first-list'><b>1.2</b><br/>The term "you" or "your" refers to any user of the Service, in the capacity of a Customer, Sender, Recipient, or Visitor of the Application.</p>
                <p className='terms-first-list'><b>1.3</b><br/>These Terms and Conditions are effective as of the date first written. The Terms and Conditions may change from time to time, but any change will only be effective from the date it is made and will not change the terms on which you previously used the Service.</p>
                <p className='terms-first-list'><b>1.4</b><br/>The Service was created to assist Customers with sending  INR(D) worldwide to and receiving money from family and friends around the world. For security reasons, we recommend that you only send  INR(D) worldwide to people you know personally. You must not use the Service to send  INR(D) worldwide to strangers.</p>
                <p className='terms-first-list'><b>1.5</b><br/>By using the Service you authorize us to access all information relating to you (including personal information relating to access and use of the Application by you and the transactions performed by you) in accordance with our Privacy Policy. Along with these Terms and Conditions, you accept and agree to be bound by the Privacy Policy.</p>

                <li><b>Definations</b></li>
                <p>In these Terms and Conditions, unless the context otherwise requires, the following words and phrases shall have the meaning assigned to them hereunder.</p>
                <p><b>"Alerts"</b>means advice, caution or notice relating to the Service issued or to be issued by us to you through a text message or an email.</p>
                <p><b>"Beneficiary/Receiver" </b>refers to the person or bank account designated by you to receive money through the Service.</p>
                <p><b>"Business Day" </b>means any day that is not a Saturday, Sunday, bank or public holiday in the locality/country where the Visitor is located and/or the Receiver receives the payment.</p>
                <p><b>"Customer/User"</b>means a registered user of the Service.</p>
                <p><b>"Customer Account"</b>means the account opened by the Customer on the Application in accordance with the Terms and Conditions.</p>
                <p><b>"Money Transfer Funds" </b>means all monies received or collected from or on behalf of the Customer in respect of all Transactions initiated by the Customer, including, but not limited to, Transaction Amount and all fees and charges.</p>
                <p><b>"Payment Account" </b>means the bank account details of the Customer provided to Moneyfirst at the time of registration for the Service, to be used to transfer the Transaction Amount to the Beneficiary and to pay the applicable service charges for the use of Service.</p>
                <p><b>"Payment Instrument" </b>means a valid instrument of payment such as a bank account.</p>
                <p><b>"Registered User ID"</b>means the unique identifier chosen by the Customer at the time of registration on the Application to access the Application and any Service.</p>
                <p><b>"Registered User Password"</b>"Registered User Password"</p>
                <p><b>"Sender" </b>means someone who uses the Service to send  INR(D) worldwide.</p>
                <p><b>"Service Provider"</b>means a local bank, money exchange house, financial institution or other third-party service provider with whom Moneyfirst has relationship with for providing the Service.</p>
                <p><b>"Supervisory Authority"</b>means Consumer Financial Protection Bureau, pursuant to the enactment of Dodd-Frank Wall Street Reform and Consumer Protection Act and any other applicable regulating authority.</p>
                <p><b>"Transaction" </b>means a specific instruction made by the Customer/User to send  INR(D) worldwide using the Service to a Beneficiary/Receiver.</p>
                <p><b>"Transaction Amount"</b>means the amount of money that the Customer/User wishes to send to the Beneficiary/Receiver, excluding any applicable fees.</p>
                <p><b>"Visitor"</b>means any person, who accesses or visits the Application, whether or not such person has a Registered User ID and includes any Customer/User.</p>
                <p><b>"Application" </b>means www.moneyfirst.com.au domains, subdomains or subdirectories including access by computer mobile or mobile application.</p>

                <li><b>Registration</b></li>
                <p><b>3.1</b><br/>You will not access, use or attempt to use the Service as a Sender unless you are at least 18 years old, and that you have the legal capacity to form a binding legal contract in the relevant jurisdiction.</p>
                <p><b>3.2</b><br/>You shall not create more than one Registered User ID.</p>
                <p><b>3.3</b><br/>You will provide true, accurate, current and complete information concerning your identity and promptly update this information to keep it true, accurate, current and complete if it changes.</p>
                <p><b>3.4</b><br/>We may terminate your registration and refuse access to and use of the Application or Service, including the cancellation of pending transactions, if we reasonably believe that you provided information that is untrue, inaccurate, not current or incomplete or that you are using the Service in breach of these Terms and Conditions or any applicable laws, rules or regulations.</p>
                <p><b>3.5</b><br/>We may request from you, at any time and from time to time, additional information and/or proof of authenticity of any information previously provided; your continued access to the Application and the Service, including the completion of any ongoing transaction, may be subject to the receipt by us of such additional information or proof.</p>
                <p><b>3.6</b><br/>You will be solely and absolutely responsible for maintaining the secrecy and confidentiality of your Registered User ID including personal identification numbers.</p>
                <p><b>3.7</b><br/>You are solely and absolutely responsible and liable for all Transactions and activities that occur using your Registered User ID including any unauthorized use or misuse of the Registered User ID and Moneyfirst will have no obligation to verify the authenticity of any such Transaction or activity.</p>
                <p><b>3.8</b><br/>You will unconditionally indemnify us and hold us harmless against any liability, costs, damages, claims, suits, and proceedings based upon or relating to any unauthorized access and/or use of your Registered User ID.</p>
                <p><b>3.9</b><br/>Without prejudice to the foregoing Para. 3.8, you will log out from your account at the end of each session and immediately notify our customer service by Email at info@moneyfirst.com.au or by phone at 0061-474-944-241 of any suspected loss, theft or unauthorized usage of your Registered User ID and any other breach of security, any receipt of confirmation of a Transaction, fund or other activity which you did not authorize, or any inaccurate information in your Customer Account balances or transaction history.</p>
                <p><b>3.10</b><br/>To the extent permissible by applicable law, we shall have the right (but not the obligation) to require the Customer/User to communicate instructions and authorize and execute Transactions and other activities by means of secure electronic records and secure digital signatures in addition to, or in place of, the use of any password(s).</p>

                <li><b>Payment account verification</b></li>
                 <p><b>4.1</b><br/>oneyfirst may engage third-party suppliers ("Supplier") to verify your identity and your authority and access to Payment Account. By using the Service, you authorize Moneyfirst and Supplier to access third party internet sites, servers or documents, retrieve information, and use your information, with the full power and authority to do and perform each and every act and thing requisite and necessary to be done in connection with the verification.<span className='terms-four-para'>YOU ACKNOWLEDGE AND AGREE THAT WHEN MONEYFIRST OR SUPPLIER ACCESSES AND RETRIEVES INFORMATION FROM THIRD PARTY SITES, MONEYIRST AND SUPPLIER ARE ACTING AS YOUR AGENT, AND NOT THE AGENT OR ON BEHALF OF THE THIRD PARTY.</span> You agree that third party account verification providers shall be entitled to rely on the foregoing authorization.</p>
                 <p><b>4.2</b><br/>The Challenge Deposit Verification Service is an alternate method of verifying your access to an external Payment Account. By using the Challenge Deposit Verification Service, you authorize Moneyfirst and Supplier to make up to one micro value transactions  to the Payment Account specified by you. You will thereafter verify to Moneyfirst and/or Supplier the amounts deposited to the Payment Account.</p>
                 <p><b>4.3</b><br/>You agree that the results of the verification service are for use by you and Moneyfirst and its Service Providers only in connection with the Service.</p>

                 <li><b>Use of the application</b></li>
                 <p><b>5.1</b><br/>Moneyfirst reserves the right to change the Application or any feature or Service of the Application. Moneyfirst may advise you of any such changes by sending you an Alert or by notification on the Application.</p>
                 <p><b>5.2</b><br/>You are responsible for obtaining, maintaining and ensuring compatibility of your own equipment when using the Application. Moneyfirst will not be responsible for any loss of or damage to your data, software, computer, telecommunications or other equipment caused by your use of the Application. You are responsible for ensuring that your equipment is free from viruses and other malware. Moneyfirst will not be responsible for any losses incurred by your failure to do this.</p>
                 <p><b>5.3</b><br/>Moneyfirst does not warrant that your access to the Application and use of the Service will be uninterrupted, continuous or error free or free from infection by viruses or anything else with contaminating or destructive properties. Moneyfirst shall not be liable to you for any loss, expense, damage, delay, costs, or compensation (whether direct or indirect or consequential) which may be suffered by you or incurred by you arising from or in any way connected with any interruption or inability to access the Application.</p>

                <li><b>Conduct of customers/users</b></li>
                <p><b>6.1</b><br/>For each Transaction that you submit, you will be charged a service fee/charge as applicable in addition to the Transaction Amount. Payment becomes due at the time that you submit your Transaction. You authorize Moneyfirst to charge your Payment Account for the Money Transfer Funds. You understand and acknowledge that Moneyfirst has no obligation to process or complete a Transaction if Moneyfirst is unable for any reason to obtain authorization or settlement of the funds from charging your Payment Account.</p>
                <p><b>6.2</b><br/>In the event the charge to your Payment Account is subsequently returned, charged-back or cancelled for any reason, and Moneyfirst has already processed your Transaction, you will be responsible to Moneyfirst for the amount. In such an event, we reserve the right to mark lien on the Beneficiary/Receiver account where such funds were credited and continue the lien until such time the funds are returned. You agree to pay such amount, plus any applicable service fee or in-sufficient funds fee applicable to the return, to Moneyfirst immediately upon demand.</p>
                <p><b>6.3</b><br/>You will provide true, accurate, current and complete information regarding the Beneficiary/Receiver for all Transactions.</p>
                <p><b>6.4</b><br/>We do not accept any liability for damages resulting from non-payment or delay in payment of a money transfer to a Beneficiary/Receiver or failure to perform a transaction under the Service.</p>
                <p><b>6.5</b><br/>When you pay for a Transaction in one currency and the Receiver is paid in another currency, there will be a difference between the exchange rate at which we buy foreign currency and the exchange rate provided to you. We and our Service Providers may have a profit or loss in these circumstances because the rate at which we or our Service Providers obtain foreign currency may not be the same as the exchange rate provided to you. If a Receiver's account is denominated in another currency, there may be delays, additional charges or different exchange rates. Please ensure the currency requested for the transaction is the same as the currency of the account where the funds are to be delivered. If additional charges are incurred due to incorrect information provided by you, the amount received by the Receiver will be reduced by the amount of such additional charges.</p>
                <p><b>6.6</b><br/>It is your responsibility to ensure all transaction details are accurate prior to submission of the Transaction. You will be given the opportunity to review the transactions details before submission of the Transaction for processing. Once a Transaction has been submitted for processing it is not normally possible to change the details.</p>
                <p><b>6.7</b><br/>We are not responsible for any fees or charges you may incur when utilizing a particular Payment Instrument to fund a Transaction. These may include but are not limited to unauthorized overdraft fees imposed by banks if there are insufficient funds in your bank account or "cash advance" fees, credit/debit card charges and additional interest which may be imposed by your bank if they treat the Service as a credit transaction rather than a cash transaction.</p>
                <p><b>6.8</b><br/>You will use the Service only to send  INR(D) worldwide to people that you know personally and not to pay for any goods or services. If, in breach of this clause, you choose to pay third parties for goods and services using the Service, you acknowledge that we have no control over, and are not responsible for, the quality, safety, legality, or delivery of such goods or services and that any such use of the Service is entirely at your own risk. If we reasonably believe you are using the Service to purchase goods or services, we reserve the right to cancel your transaction(s).</p>
                <p><b>6.9</b><br/><b>Both Customer and Receiver will act on behalf of their respective selves. You may not submit or receive a Transaction on behalf of a third party. If you intend to submit or receive a Transaction on behalf of a company, business or a third party individual, you must first inform us of your desire to do so and provide us with such additional information as we deem fit about the company, business or third party individual, in order that we may decide whether to permit the transaction.</b></p>
                <p><b>6.10</b><br/>In using the Service you will comply with these Terms and Conditions as well as any applicable laws, rules or regulations. You will not use the Service to send  INR(D) worldwide:</p>
                <p><b>6.10.1</b><br/>to a recipient who has violated the Terms and Conditions, or</p>
                <p><b>6.10.2</b><br/>in connection with illegal activity including without limitation money-laundering, fraud and the funding of terrorist organizations.</p>
                <p><b>6.11</b><br/>If you use the Service in connection with illegal activity or any activity which seem suspicious, we will report your Transaction(s) to the appropriate legal authorities.</p>
                <p><b>6.12</b><br/>We may, as is necessary to provide the Service, store all information required of a Receiver to prove his or her identity or associated with the Receiver's specific Transaction. Such proofs may include, but are not limited to, a suitable form of valid, unexpired identification from a list of acceptable documents provided by the Service Provider, and/or a transaction tracking number, a personal identification number (PIN), a "password," a "secret word" or other similar identifiers as we or our Service Provider may deem fit.</p>
                <p><b>6.13</b><br/>In case we do not receive the Transaction Amount and fee/charges, and the Transaction Amount is credited/paid out to the Beneficiary/Receiver, Moneyfirst shall have the right to recover the Transaction Amount along with all associated charges from the Customer. By initiating a Transaction on the Application, you are aware and agree that the funds may be credited to the account of the Beneficiary prior to receipt of funds from you by Moneyfirst. In such an event, we reserve the right to mark lien on the Beneficiary/Receiver account where such funds were credited and continue the lien until such time the funds are returned. You further agree that a mere demand from Moneyfirst in such circumstances shall be good reason for you to pay the shortfall/loss without any demur or delay.</p>
                <p><b>6.14</b><br/>The Service Provider may credit/payout the Transaction Amount only after it has received a confirmation that funds have been received in its bank account. If it comes to the notice of Moneyfirst that you had insufficient funds in the Payment Account from which you requested the Transaction or you have provided wrong details of designated bank account, Monet or the Service Provider may cancel the Transaction and you shall bear full liability and responsibility for the same. In the event the insufficiency of funds is learned by Moneyfirst after the Recipient has received the Transaction Amount, you will be liable to reimburse Moneyfirst (as applicable) of the amount remitted and any other charges and costs incurred by Moneyfirst and/or the Service Provider. You agree to pay such amount immediately upon Moneyfirst demand. Moneyfirst shall also be entitled to inform any credit bureau or any other person or entity including the law enforcement agencies if you fail to pay/reimburse such amount or any part thereof.</p>

                <li><b>Other terms</b></li>
                <p><b>7.1</b><br/>Subject to these Terms and Conditions, we agree to provide the Service using reasonable care. The Service may not be available in whole or in part in certain regions, countries, or jurisdictions.</p>
                <p><b>7.2</b><br/>We are not obliged to process any particular Transaction. When you submit a Transaction, you are requesting that we process the Transaction on your behalf. We may, in our sole discretion, choose whether or not to accept the offer to process that Transaction. However, if we decide not to process the Transaction, we will notify you promptly of that decision and repay the money paid to us.</p>
                <p><b>7.3</b><br/>We reserve the right to modify or discontinue the Service or any part of the Service without notice, at any time and from time to time. We may, in our absolute discretion or subject to such applicable laws, refuse any Transaction or limit the amount transferred, either on a per transaction basis or on an aggregate basis, and either on individual accounts or on related accounts.</p>
                <p><b>7.4</b><br/>We will attempt to process Transactions promptly, but any transaction may be delayed or cancelled for a number of reasons including but not limited to: our efforts to verify your identity; to validate your transaction instructions; to contact you; or otherwise to comply with applicable law; or due to variations in business hours and currency availability.</p>
                <p><b>7.5</b><br/>We will attempt to provide Customer and Receiver with up to date information regarding the location and opening hours of our Service Providers by means of information on the Application. However, you agree that we shall not be held responsible for any inaccuracies that may appear in that information or any consequential loss which may result from incorrect or incomplete information.</p>
                <p><b>7.6</b><br/>We conduct our services in a transparent manner and do not withhold any information from Customer pertaining to Customer's Transaction. The requisite information pertaining to Customer's Transaction is disclosed to Customer in the manner and form required by the Supervisory Authority.</p>
                <p><b>7.7</b><br/>Reference to a particular gender shall be deemed to include a reference to the other genders and singular shall include the plural and vice versa and the word "includes" should be construed as if the words "without limitation" appear thereafter.</p>

                
            </ol>
        </div>
    </div>

    </>
  )
}

export default Terms_Condition